apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: step-3-pushsecret-chart
  namespace: vault #TODO
  labels:
    project: multicluster
    cluster-info: {{ .Values.openshift.cluster }}