{{- range $v := .Values.cluster.cluster_list }}
---
apiVersion: v1
kind: Pod
metadata:
  name: create-kubeconfig-pod-{{ $v.name }}
  namespace: {{ $.Values.project }}-{{ $.Values.stage }}
spec:
  containers:
  - name: script-runner
    image: registry.redhat.io/openshift4/ose-tools-rhel8:latest
    command: ["/bin/bash", "/scripts/bash.sh"]
    env:
    - name: SECRET_NAME
      value: mc-{{ $v.name }}-to-{{ $.Values.cluster.short_name }}-kubeconfig
    - name: NAMESPACE
      value: {{ $.Values.project }}-{{ $.Values.stage }}
    - name: SERVICE_ACCOUNT
      value: mc-{{ $v.name }}-to-{{ $.Values.cluster.short_name }}
    - name: CLUSTER_NAME
      value: {{ $.Values.cluster.short_name }}
    - name: SERVER
      value: {{ $.Values.cluster.server }}
    - name: TARGET_CLUSTER_NAME
      value: {{ $v.name}}-cluster
    volumeMounts:
    - name: cmap-clustersecrets
      mountPath: /scripts
      readOnly: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never
  serviceAccountName: {{ $.Values.serviceAccountName }}
  volumes:
  - name: cmap-clustersecrets
    configMap:
      name: create-cluster-secrets-configmap
      items:
      - key: bash.sh
        path: bash.sh
{{- end }}
