apiVersion: v1
kind: ConfigMap
metadata:
  name: create-cluster-secrets-configmap
  namespace: {{ .Values.project }}-{{ .Values.stage }}
data:
  bash.sh: |
    #!/bin/bash
    echo "############### EXACT VARIABLES ################"
    export SA_TOKEN_NAME=$(oc get secret | grep $SERVICE_ACCOUNT | grep token | awk '{print $1}')
    export SA_SECRET_TOKEN=$(oc get secret $SA_TOKEN_NAME -n $NAMESPACE -o jsonpath='{.data..token}' | base64 --decode)
    export CLUSTER_CA_CERT=$(oc get secret $SA_TOKEN_NAME -n $NAMESPACE -ojsonpath='{.data..ca\.crt}')

    echo "SERVICE ACCOUNT: $SERVICE_ACCOUNT"
    echo "SA_TOKEN_NAME: $SA_TOKEN_NAME"
    echo "SA_SECRET_TOKEN : $SA_SECRET_TOKEN"
    echo "CLUSTER_CA_CERT: $CLUSTER_CA_CERT"

    echo "############### CREATE KUBECONFIG ################"

    KUBECONFIG_CONTENT=$(cat <<EOF
    apiVersion: v1
    kind: Config
    clusters:
    - name: ${CLUSTER_NAME}
      cluster:
        certificate-authority-data: ${CLUSTER_CA_CERT}
        server: ${SERVER}
    contexts:
    - name: ${SERVICE_ACCOUNT}@${CLUSTER_NAME}
      context:
        cluster: ${CLUSTER_NAME}
        namespace: ${NAMESPACE}
        user: ${SERVICE_ACCOUNT}
    users:
    - name: ${SERVICE_ACCOUNT}
      user:
        token: ${SA_SECRET_TOKEN}
    current-context: ${SERVICE_ACCOUNT}@${DESTINATION_CLUSTER}
    EOF
    )
    
    # Output to kubeconfig file
    echo "${KUBECONFIG_CONTENT}" > /tmp/kubeconfig.yaml 
    echo $KUBECONFIG_CONTENT


    echo "############### CREATE SECRET ################"
    
    oc delete secret $SECRET_NAME -n $NAMESPACE

    oc create secret generic $SECRET_NAME \
      --from-literal=secret-key-ca-cert=$CLUSTER_CA_CERT \
      --from-literal=secret-key-sa-secret-token=$SA_SECRET_TOKEN \
      --from-file=secret-key-kubeconfig=/tmp/kubeconfig.yaml \
      -n $NAMESPACE

    oc label secret $SECRET_NAME project=multicluster -n $NAMESPACE
