# ServiceAccount which will be used for creating the Kubeconfig Secrets
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.project }}-{{ .Values.stage }}
  labels:
    stage: {{ .Values.stage }}
