{{- range $v := .Values.cluster.cluster_list }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-{{ $v.name}}-to-{{ $.Values.cluster.short_name }}
  namespace: {{ $.Values.project }}-{{ $.Values.stage }}
  labels:
    project: multicluster
{{- end }}