{{- range $v := .Values.cluster.cluster_list }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-vault-all-secrets-mc-{{ $v.name }}-to-{{ $.Values.cluster.short_name }}-kubeconfig
  namespace: {{ $.Values.project }}-{{ $.Values.stage }}
spec:
  secretStoreRefs:
    - name: {{ $.Values.externalSecret.secretStoreRef.name }}
      kind: {{ $.Values.externalSecret.secretStoreRef.kind }}
  selector:
    secret:
      name: mc-{{ $v.name }}-to-{{ $.Values.cluster.short_name }}-kubeconfig
  refreshInterval: {{ $.Values.externalSecret.pushSecret.refreshInterval }}
  data:
  {{- range $.Values.externalSecret.pushSecret.data }}
    - match:
        secretKey: {{ .secretKey  }}
        remoteRef:
          {{- if contains "kubeconfig" .secretKey }}
          property: mc-{{ $v.name }}-to-{{ $.Values.cluster.short_name }}-kubeconfig
          {{- else }}
          property: {{ .vaultProperty }}
          {{- end }}
          remoteKey: {{ .vaultPath }}
  {{- end }}
{{- end }}
