{{- range $v := .Values.cluster.cluster_list }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pullsecret-vault-all-secrets-{{ $v.name }}
  namespace: {{ $.Values.project }}-{{ $.Values.stage }}
spec:
  refreshInterval: {{ $.Values.externalSecret.pullSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecret.secretStoreRef.kind }}
    name: {{ $.Values.externalSecret.secretStoreRef.name }}
  target:
    name: istio-remote-secret-{{ $v.name }}-cluster
    template:
      metadata:
        annotations:
          networking.istio.io/cluster: {{ $v.name }}-cluster
        labels:
          istio/multiCluster: 'true'
  data:
    - secretKey: {{ $v.name }}-cluster
      remoteRef:
        key: kv/data/multicluster/{{ $v.name }}/kubeconfig
        property: mc-{{ $.Values.cluster.short_name }}-to-{{ $v.name }}-kubeconfig
{{- end }}
