apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: step-1-create-serviceaccount-chart
  namespace: yuya-test #TODO
  labels:
    project: multicluster
    cluster-info: {{ .Values.openshiftCluster }}