{{- range $v := .Values.relatedClusters }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: step1-create-serviceaccount-chart-{{ $v.name}}
  namespace: yuya-test
  labels:
    project: multicluster
    cluster-info: {{ .Values.openshiftCluster }}
{{- end }}