apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: step-2-create-secret-chart
  namespace: yuya-test #TODO
  labels:
    project: multicluster
    cluster-info: {{ .Values.openshiftCluster }}