apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "cluster-c-xxxx-qa01"
  template:
    metadata:
      name: "test-argocd-app"
    spec:
      project: default
      source:
        repoURL: "https://github.com/yuyatinnefeld/yu-argocd-test.git"
        targetRevision: HEAD
        path: helmcharts-test1
        helm:
          valueFiles:
            - values-env-satu.yaml
          parameters:
            - name: project
              value: "argocd-project"
            - name: stage
              value: "argocd-stage"
            - name: openshift.cluster
              value: "{{cluster}}"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
