apiVersion: v1
kind: Pod
metadata:
  name: create-secrets-pod
  namespace: vault
spec:
  containers:
  - name: script-runner
    image: bitnami/kubectl
    command: ["/bin/bash", "/scripts/bash.sh"]
    env:
    - name: SECRET_NAME
      value: mc-access-to-okpd-kubeconfig
    - name: NAMESPACE
      value: yuya-test
    - name: SERVICE_ACCOUNT
      value: sa-for-cluster-kommunikation
    - name: DESTINATION_CLUSTER
      value: okpd
    - name: SERVER
      value: okpd-server
    - name: TARGET_CLUSTER_NAME
      value: okpd-cluster
    volumeMounts:
    - name: cmap-clustersecrets
      mountPath: /scripts
      readOnly: true
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never
  serviceAccountName: sa-for-script
  volumes:
  - name: cmap-clustersecrets
    configMap:
      name: create-cluster-secrets-configmap
      items:
      - key: bash.sh
        path: bash.sh