apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pullsecret-vault-all-secrets
  namespace: vault
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-backend-secret-store # openshift > vault
  refreshInterval: 1m
  target:
    name: istio-remote-secret-okpc-cluster-test  # test secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: secret-key-kubeconfig
      remoteRef:
        key: kv/data/multicluster/okpd/kubeconfig/test # path for test
        property: test-mc-access-to-okpd-kubeconfig # test secret
