apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-vault-mc-access-to-okpd-kubeconfig
  namespace: vault
spec:
  data:
    - match:
        remoteRef:
          property: mc-access-to-okpd-kubeconfig
          remoteKey: kv/data/multicluster/okpd/kubeconfig/test # path for test
        secretKey: secret-key-kubeconfig
  refreshInterval: 60s
  secretStoreRefs:
    - kind: SecretStore
      name: vault-backend-secret-store
  selector:
    secret:
      name: test-mc-access-to-okpd-kubeconfig  # test secret
